title: "Okay dude, what the flip?"
description: "My little spot on the internet"

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"